### ISSUE TITLE
Failed to load on Azure

### ISSUE THREAD

**Issue by supercaracal** [supercaracal/duel-shooting-online#4]
```
Mon Nov 07 2016 02:05:47 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
SyntaxError: Error parsing C:\DWASFiles\Sites\duel-shooting-online\DynamicCache\wwwroot\node_modules\express\package.json: Unexpected token � in JSON at position 0
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:172:20)
    at Function.Module._resolveFilename (module.js:438:25)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\DWASFiles\Sites\duel-shooting-online\DynamicCache\wwwroot\web.js:1:77)
    at Module._compile (module.js:541:32)
Application has thrown an uncaught exception and is terminated:
SyntaxError: Error parsing C:\DWASFiles\Sites\duel-shooting-online\DynamicCache\wwwroot\node_modules\express\package.json: Unexpected token � in JSON at position 0
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:172:20)
    at Function.Module._resolveFilename (module.js:438:25)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\DWASFiles\Sites\duel-shooting-online\DynamicCache\wwwroot\web.js:1:77)
    at Module._compile (module.js:541:32)
```

**Comment by supercaracal** [comment]
Fixed http://duel-shooting-online.azurewebsites.net/
